### ISSUE TITLE
#haq-gest | About Us page - org link option

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#100]
![image](https://user-images.githubusercontent.com/64309749/188065628-c1ba7a27-9bbd-4134-bed0-1895bd9f5eef.png)

Currently, there's 3 options - Github, LinkedIn, and twitter. Even if the link is not provided, the logos show up. For an organisation, their website is the most important. No option to give website link. 

My recommendation

1. Website 
2. Email
3. Twitter
4. Github
5. LinkedIn
6. Facebook

Organisation and team should have an option to enter one or more of the above 6, and if a link is not added, that logo shouldn't show up.

**Comment by aashimgarg** [comment]
> ![image](https://user-images.githubusercontent.com/64309749/188065628-c1ba7a27-9bbd-4134-bed0-1895bd9f5eef.png)
> 
> Currently, there's 3 options - Github, LinkedIn, and twitter. Even if the link is not provided, the logos show up. For an organisation, their website is the most important. No option to give website link.
> 
> My recommendation
> 
>     1. Website
> 
>     2. Email
> 
>     3. Twitter
> 
>     4. Github
> 
>     5. LinkedIn
> 
>     6. Facebook
> 
> 
> Organisation and team should have an option to enter one or more of the above 6, and if a link is not added, that logo shouldn't show up.

for the website link option, should I give the website link to the card like onClicking the card the website should open or should I provide the icon ? @arunsud @PixeledCode

**Comment by PixeledCode** [comment]
I think giving ‘a’ tag to both logo and org name should work.

**Comment by aashimgarg** [comment]
Fixed!!
