### ISSUE TITLE
#haq-gest | Footer not updating when content is changed on strapi

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#101]
![image](https://user-images.githubusercontent.com/64309749/188067214-323f992a-2002-4f81-b3ef-3aece1ac1b9f.png)

I've edited content on the footer (as above), and it doesn't change the footer on the frontend. 

![image](https://user-images.githubusercontent.com/64309749/188067493-385d0215-280f-4909-a938-9b96c0b14d09.png)

**Comment by aashimgarg** [comment]
> ![image](https://user-images.githubusercontent.com/64309749/188067214-323f992a-2002-4f81-b3ef-3aece1ac1b9f.png)
> 
> I've edited content on the footer (as above), and it doesn't change the footer on the frontend.
> 
> ![image](https://user-images.githubusercontent.com/64309749/188067493-385d0215-280f-4909-a938-9b96c0b14d09.png)

yea when i was connecting to the strapi there was no footer data . So now we have data and images i connect with strapi

**Comment by aashimgarg** [comment]
Fixed !
