### ISSUE TITLE
#haq-gest | Hero section heading and sub-heading

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#93]
![image](https://user-images.githubusercontent.com/64309749/188062646-f3cd351c-0280-4695-b5c1-7f3cd4cf44fa.png)

The hero section heading is current not editable via strapi. Additionally, while the sub-heading is editable, the font size is too small.

**Comment by aashimgarg** [comment]
> ![image](https://user-images.githubusercontent.com/64309749/188062646-f3cd351c-0280-4695-b5c1-7f3cd4cf44fa.png)
> 
![Screenshot from 2022-09-02 11-52-52](https://user-images.githubusercontent.com/55639487/188072066-b72c8605-cc22-4995-945c-0c5b62f9f080.png)

> The hero section heading is current not editable via strapi. Additionally, while the sub-heading is editable, the font size is too small.


is this font size good ? @arunsud

**Comment by arunsud** [comment]
Thanks @aashimgarg - can the font size be increased slightly more?

**Comment by aashimgarg** [comment]
> Thanks @aashimgarg - can the font size be increased slightly more?
![Screenshot from 2022-09-02 12-14-28](https://user-images.githubusercontent.com/55639487/188075547-bd1430b3-b955-455d-858d-c6a9220c434f.png)

**Comment by arunsud** [comment]
Works @aashimgarg
