### ISSUE TITLE
#haq-gest | Nav Bar reordering, editing

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#97]
![image](https://user-images.githubusercontent.com/64309749/188063334-00da6a6b-a41a-4286-9cff-c2ee73363210.png)

Nav bar should have the following three options

1. `Datasets` with 3 sub menus - `Summary`, `Schemes`, `All Datasets`
2. Data Stories
3. About Us

Currently the nav bar is not editable via strapi. May not be necessary for the current iteration.

**Comment by aashimgarg** [comment]
Fixed
