### ISSUE TITLE
#haq-gest | Carousel - link not added in the frontend, "Explore More" button not clickable

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#98]
![image](https://user-images.githubusercontent.com/64309749/188064560-cea1d8b9-33dd-4dc0-b7da-ce8664c42ab6.png)

See above. I've added an internal link to a dataset in the carousel. However, when I click `Explore More` button, it's not clickable, and doesn't redirect to the dataset page. 

![image](https://user-images.githubusercontent.com/64309749/188064658-7af5220c-f2ce-4869-acca-d7e469daee0c.png)

**Comment by aashimgarg** [comment]
Giving the link to the explore more button. @arunsud

**Comment by aashimgarg** [comment]
Fixed
