### ISSUE TITLE
#haq-gest | Team page - option to indicate the organisation

### ISSUE THREAD

**Issue by arunsud** [CivicDataLab/opub#99]
![image](https://user-images.githubusercontent.com/64309749/188065146-cf50d043-6453-4d5a-884b-f9673d3289df.png)

Since the project is a partnership between 3 organisations, when we add the team members' names, it'd be better if there's an option in strapi to add the name. Currently, I've added CDL along with the role (see above). 

![image](https://user-images.githubusercontent.com/64309749/188065400-2515f72a-98ca-426e-a852-1ed280fe1ed0.png)

(Surprisingly, external links are showing up here although it's not working for the curated stories on the homepage)

**Comment by aashimgarg** [comment]
Fixed
